Basically completed
casdoor/casdoor-android-sdk-old pull request #1
Opened 2021-08-09 12:54 UTC by 1340908470

SDK with README.md

2021-08-09 13:00 UTC, 1340908470 commented
[Demo app using this sdk](https://bupteducn-my.sharepoint.com/:u:/g/personal/1340908470_bupt_edu_cn/EUpLpCXpjd1IgJEJ45UBUT0BnP-vZqdICtJ9hl1bGuY2XQ?e=592rfJ)

2021-08-09 13:03 UTC, 1340908470 commented
@hsluoyz

2021-08-10 01:48 UTC, hsluoyz requested changes

2021-08-10 01:48 UTC, hsluoyz commented on .gitignore
> +/build
why delete?

2021-08-10 01:49 UTC, hsluoyz commented
@sh1luo @tangyang9464 @Kininaru @WindSpiritSR plz review

2021-08-12 03:21 UTC, merged